/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Base_de_Datos;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author ITSYADM
 */
public class Curricular extends javax.swing.JFrame {
  
    Base_de_Datos c=new Base_de_Datos();
     String sql;
    /**
     * Creates new form Curricular
     */
    public Curricular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_buscarr = new javax.swing.JButton();
        lbl_malla_curricular = new javax.swing.JLabel();
        lbl_identidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        txt_identidad = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_fecha_creacion = new javax.swing.JTextField();
        txt_fecha_modificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_modificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(204, 0, 204));
        btn_modificar.setText("Modificar");
        btn_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(204, 0, 204));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(204, 0, 204));
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_buscarr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_buscarr.setForeground(new java.awt.Color(204, 0, 204));
        btn_buscarr.setText("Buscar");
        btn_buscarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarrActionPerformed(evt);
            }
        });

        lbl_malla_curricular.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_malla_curricular.setForeground(new java.awt.Color(204, 0, 0));
        lbl_malla_curricular.setText("Malla Curricular");

        lbl_identidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_identidad.setForeground(new java.awt.Color(0, 0, 204));
        lbl_identidad.setText("Identidad");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Fecha Creación");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Fecha Modificación");

        btn_nuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(204, 0, 204));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        txt_identidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txt_fecha_creacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txt_fecha_modificacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Estado");

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_identidad)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_fecha_modificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(txt_fecha_creacion, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarr)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lbl_malla_curricular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_malla_curricular)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_identidad)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txt_fecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txt_fecha_modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_buscarr)
                    .addComponent(btn_nuevo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        try {
            if (actualizar()){
            }else{
                JOptionPane.showMessageDialog(null, "error al modificar datos");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Curricular.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_modificarActionPerformed
public boolean actualizar() throws SQLException{
boolean estado=false;
     try {
         if (c.Conectar()){
              sql="update curriculum set nombre='"+txt_nombre.getText()+"',fecha_modificacion='"+txt_fecha_modificacion.getText()+"',fecha_creacion='"+txt_fecha_creacion.getText()+"',fecha modificacion="+String.valueOf(txt_fecha_modificacion.getText())+" where identidad="+String.valueOf(txt_identidad.getText());
              
             if(c.ejecutar(sql)){
                 estado=true;
                 JOptionPane.showMessageDialog(null, "Se ha  modificado correctamente en la base de datos");
             }
             c.desconectar();             
         }
         else{
           JOptionPane.showMessageDialog(null, "no se pudo conectar a la base de Dato verifique");  
         }
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Curricular.class.getName()).log(Level.SEVERE, null, ex);
     }
return estado;
}
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        try {
            if (eliminar()){
                this.txt_identidad.setText("");
                this.txt_nombre.setText("");
                this.txt_fecha_creacion.setText("");
                this.txt_fecha_modificacion.setText("");
                //this.cmb_estado.getSelectedItem("");
            }else{

                JOptionPane.showMessageDialog(null, "error guardando datos");
            }         // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Curricular.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed
public boolean eliminar() throws SQLException{
boolean estado=false;
     try {
         if (c.Conectar()){
             sql="delete from curricular where identidad="+String.valueOf(txt_identidad.getText())+""; 
             //sql="insert into persona values("+Integer.parseInt(this.jTextField1.getText())+",'"+this.jTextField4.getText()+"','"+this.jTextField2.getText()+"','"+this.jComboBox1.getSelectedItem()+"',"+Integer.parseInt(this.jTextField4.getText())+")";
              // sql="insert into persona values(3,'Maria','Perez','Mujer',25)";
              
             if(c.ejecutar(sql)){
                 estado=true;
                 JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente en la base de datos");
             }
             c.desconectar();             
             
         }
         else{
           JOptionPane.showMessageDialog(null, " No se pudido conectar a la base de Datos por favor verifique");  
         }
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Curricular.class.getName()).log(Level.SEVERE, null, ex);
     }


return estado;

}
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
            if (guardar()){
                btn_modificar.setEnabled(true);
                btn_eliminar.setEnabled(true);
                txt_identidad.setEnabled(false);
            }else{

                JOptionPane.showMessageDialog(null, "Error al momento de guardar datos");
            }         // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Curricular.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    public boolean guardar() throws SQLException{
boolean estado=false;
     try {
         if (c.Conectar()){
             sql="insert into curricular values("+"'"+txt_identidad.getText()+"','"+txt_nombre.getText()+"','"+cmb_estado.getSelectedItem()+"','"+txt_fecha_creacion.getText()+"','"+txt_fecha_modificacion.getText()+"')";
             
             if(c.ejecutar(sql)){
                 estado=true;
                 JOptionPane.showMessageDialog(null, "Se ha Guardado correctamente en la base de datos");
             }
             c.desconectar();             
             
         }
         else{
           JOptionPane.showMessageDialog(null, "No se ha podido conectar a la base de Datos por favor verifique");  
         }
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Curricular.class.getName()).log(Level.SEVERE, null, ex);
     }


return estado;

}
    private void btn_buscarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarrActionPerformed
        // TODO add your handling code here:
        if(buscar(txt_identidad.getText())){

            btn_guardar.setEnabled(false);
            btn_nuevo.setEnabled(false);
            txt_identidad.setEnabled(false);

        }else{
            JOptionPane.showMessageDialog(null,"Datos no encontrados en la base de datos");
            btn_buscar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_eliminar.setEnabled(false);
        }

    }//GEN-LAST:event_btn_buscarrActionPerformed
 private boolean buscar(String ci){
boolean estado=false;
     try {
         if(c.Conectar()){
          sql="select * from curricular where identidad="+ci+";";  
          ResultSet regs=c.seleccionar(sql);
         if (regs.next()){
        txt_identidad.setText(String.valueOf(regs.getInt("identidad")));
        txt_nombre.setText(regs.getString("nombre"));
        cmb_estado.setSelectedIndex(regs.getSelectedIndex("estado"));
        txt_fecha_creacion.setText(regs.getString("fecha creacion"));
        txt_fecha_modificacion.setText(regs.getString("fecha modificacion"));
         estado=true;
         }   
  }
         c.desconectar();
     } catch (SQLException ex) {
         Logger.getLogger(malla.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(pedidos.class.getName()).log(Level.SEVERE, null, ex);
     }
return estado;
}
    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        this.txt_identidad.setText("");
        this.txt_nombre.setText("");
        this.txt_fecha_creacion.setText("");
        this.txt_fecha_modificacion.setText("");
        this.cmb_estado.getSelectedItem();
        btn_buscar.setEnabled(true);
        txt_identidad.setEnabled(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed
 private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         if(buscarxt_id(txt_identidad.getText())){
             
  
         btn_guardar.setEnabled(false);
         btn_nuevo.setEnabled(false);
         txt_identidad.setEnabled(false);
   
         }else{
   JOptionPane.showMessageDialog(null,"Datos no encontrados en la base de datos"); 
         btn_buscar.setEnabled(false);
         btn_modificar.setEnabled(false);
         btn_eliminar.setEnabled(false);
       } 
    
    }                                          

 
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Curricular().setVisible(true);
            }
        });
    }

     
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_buscar2;
    private javax.swing.JButton btn_buscarr;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_identidad;
    private javax.swing.JLabel lbl_malla_curricular;
    private javax.swing.JTextField txt_fecha_creacion;
    private javax.swing.JTextField txt_fecha_modificacion;
    private javax.swing.JTextField txt_identidad;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private boolean buscarxt_id(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
